[package]
name = "fast"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
tokio = { version = "1", features = ["full"] }
crossbeam-queue = "0.3"

[build-dependencies]
bindgen = "0.71.0"

